<?php

declare(strict_types=1);

namespace Eddieodira\Messager\Config;

use CodeIgniter\Config\BaseConfig;

class Bulksms extends BaseConfig
{
    /**
     * Here you can set the connection that the email Teemplate should use when
     * storing and restoring a cart.
     */
    public string $emailTemplateTable = 'email_templates';

    /**
     * Here you can set the connection that the shoppingcart should use when
     * storing and restoring a cart.
    */
    public string $smsTemplateTable = 'sms_templates';

    /**
    * Unique identifier assigned to your HostPinnacle account.
    * Often required for authentication alongside password or API key.
    */
    public string $userId = 'Hamicollege';

    /**
     * Secret password linked to your HostPinnacle account.
     * Used for authentication in some API endpoints. 
     * Should always be stored securely (e.g., in .env, not hardcoded).
     */
    public string $password = '27892834@Kate';

    /**
     * API key generated by HostPinnacle for secure access to their SMS API.
     * This is the primary credential used to authorize requests.
     * Keep this private and never expose it in client-side code.
     */
    public string $apiKey = 'a3494e4f0dea066c3c1a6a85f1378f3482124150';

    /**
     * Sender ID that appears as the "from" field when recipients receive SMS.
     * It can be a name, brand, or shortcode registered with HostPinnacle.
     * Helps recipients identify the sender of the message.
     */
    public string $senderId = 'HAMICOLLEGE';

    /**
     * Base URL of HostPinnacle’s SMS API.
     * All requests (send, bulk, balance, etc.) will be appended to this root URL.
     * Centralizing it here makes the library easier to maintain if the endpoint changes.
     */
    public string $baseUrl = 'https://smsportal.hostpinnacle.co.ke/SMSApi/';

    /**
     * Maximum time (in seconds) to wait for the entire request to complete.
     * If the API takes longer than this, the request will fail.
     * Helps prevent hanging requests in production.
     */
    public int $timeout = 10;

    /**
     * Maximum time (in seconds) to wait for the initial connection to the API server.
     * If the server cannot be reached within this time, the request will fail.
     * Useful for failing fast when the API endpoint is down.
     */
    public int $connectTimeout = 5;

    /**
     * Whether to verify SSL certificates when making requests.
     * Enabled in production for security, but automatically disabled in development
     * to allow local testing with self-signed certificates.
     */
    public bool $verify = (ENVIRONMENT !== 'development');

    /**
     * Whether HTTP errors (4xx/5xx) should throw exceptions automatically.
     * Disabled here so the library can handle errors manually and return
     * standardized responses instead of breaking execution.
     */
    public bool $httpErrors = false;

    /**
     * Whether to enable verbose debugging output for requests.
     * Enabled only in development mode to log request/response details
     * for troubleshooting, but disabled in production for performance and security.
     */
    public bool $debug = (ENVIRONMENT === 'development');

}
